import Navbar from "@/components/shared/Navbar";
import { SessionProvider } from "next-auth/react";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/shared/Footer";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App Router",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <Provider>
          <Navbar></Navbar>
          <div className="min-h-screen">{children}</div>
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  );
}
